---
# Source: argo-cd/templates/argocd-repo-server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: release-name-argocd-repo-server
  namespace: default
  labels:
    helm.sh/chart: argo-cd-7.4.3-aws
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.12.0"
