version: '3.8'
services:
  vm_metrics_app:
#    build:        # To build
#      context: .
#      dockerfile: Dockerfile
    image: docker.io/skmaifujalam/hive_metrics:v2
    ports:
      - "5000:5000"
    networks:
      - my_network


  haproxy-nginx:
    image: docker.io/skmaifujalam/hive_test:v1
    ports:
      - "80:80"  # Expose port 80 for HAProxy
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
