# First install prometheus-operator:
#
# helm install coreos/prometheus-operator --name prometheus-operator
#

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  # Namespace of prometheus operator
  namespace: kube-prometheus-stack
  labels:
    prometheus: mon
spec:
  namespaceSelector:
    matchNames:
    - kube-prometheus-stack
  selector:
    matchLabels:
      k8s-app: node-exporter
  endpoints:
  - port: metrics
    interval: 10s

---

apiVersion: v1
kind: Service
metadata:
  name: name-your-server-com
  namespace: kube-prometheus-stack
  labels:
    k8s-app: node-exporter
spec:
  type: ExternalName
  externalName: name.your-server.com
  clusterIP: ""
  # Maybe not relevant
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100

---

apiVersion: v1
kind: Endpoints
metadata:
  # Name must match service name
  name: name-your-server-com
  namespace: kube-prometheus-stack
  labels:
    k8s-app: node-exporter
subsets:
  - addresses:
    - ip: 172.31.0.10
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
