apiVersion: v1
kind: Endpoints
metadata:
  name: haproxy-exporter
  namespace: kube-prometheus-stack
  labels:
    app: haproxy-exporter  # To make it work with prometheus node exporter.
    instance: 172.31.0.10           # Uniquely identify the instance.
subsets:
  - addresses:
      - ip: 172.31.0.10 # Replace with your external node's IP
    ports:
      - port: 8405      # Node Exporter's port
        name: metrics

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-exporter
  namespace: kube-prometheus-stack
  labels:
    app: haproxy-exporter # To make it work with prometheus node exporter.
    instance: 172.31.0.10  # Uniquely identify the instance.
spec:
  ports:
    - port: 8405
      targetPort: metrics
  clusterIP: None # Required for headless service
  selector: {}    # No selectors since it's targeting the external `Endpoints`
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy-exporter-service-monitor
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack # Ensure this matches your Prometheus release name
    instance: 172.31.0.10  # Uniquely identify the instance.
spec:
  jobLabel: haproxy-exporter # Set the job name using this field
  selector:
    matchLabels:
      app: haproxy-exporter # To make it work with prometheus node exporter.
      instance: 172.31.0.10  # Uniquely identify the instance.
  namespaceSelector:
    matchNames:
      - kube-prometheus-stack
  endpoints:
    - port: metrics
      scheme: http
      interval: 15s
