pipeline {
    agent any
    environment {
        HELM_CHART_DIR = 'helm-chart-directory'
        HELM_VALUES_FILE = 'values.yaml'
    }
    input message: '', parameters: [
        string(name: 'REPO_NAME', defaultValue: 'https://github.com/maifujalam/k8s_aws.git', description: 'Enter the git remote name'),
        string(name: 'BRANCH_NAME', defaultValue: 'main', description: 'Enter the branch name to pull from'),
        string(name: 'FOLDER_PATH', defaultValue: 'k8s/v1.30.5/manifests', description: 'Enter the folder path name which to be helm build')
    ]
    stages {
        stage('Git Checkout') {
            steps {
                checkout scmGit(
                branches: [[name: $BRANCH_NAME]],
                userRemoteConfigs: [[url: $REPO_NAME]])
            }
        }
        stage('Render Helm Chart') {
            steps {
                script {
                    // Check if the values.yaml file has been modified
                    def changes = sh(script: "git diff --name-only HEAD HEAD~1", returnStdout: true).trim()

                    if (changes.contains(HELM_CHART_DIR + '/' + HELM_VALUES_FILE)) {
                        echo "Changes detected in ${HELM_VALUES_FILE}. Proceeding with Helm chart build."
                        currentBuild.result = 'SUCCESS'
                    } else {
                        echo "No changes detected in ${HELM_VALUES_FILE}. Skipping Helm chart build."
                        currentBuild.result = 'ABORTED'
                        error("No changes in Helm values.yaml. Skipping the build.")
                    }
                }
            }
        }

        stage('Build Helm Chart') {
            when {
                expression {
                    // Proceed only if the previous step was successful
                    return currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                script {
                    // Build and package the Helm chart
                    sh """
                        helm lint ${HELM_CHART_DIR}
                        helm package ${HELM_CHART_DIR}
                    """
                }
            }
        }

        stage('Push Helm Chart') {
            when {
                expression {
                    return currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                script {
                    // Push the packaged chart to a Helm repository (if required)
                    // Replace this with actual commands if you're pushing to a repository
                    echo "Pushing Helm chart to repository"
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished"
        }
        failure {
            echo "Pipeline failed"
        }
        success {
            echo "Helm chart build successful"
        }
    }
}

