apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-llt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sk.maifujalam@gmal.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        route53:
          region: ap-south-1
          accessKeyIDSecretRef:
#            name: prod-route53-credentials-secret
            name: letsencrypt-staging
            key: access-key-id
          secretAccessKeySecretRef:
#            name: prod-route53-credentials-secret
            name: letsencrypt-staging
            key: secret-access-key
          # (optional) you can also assume a role with these credentials
          role: arn:aws:iam::383886020191:policy/lets-encrypt_policy
