apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cluster-issuer-llt
spec:
  acme:
    server:  https://acme-v02.api.letsencrypt.org/directory
    email: sk.maifujalam@gmal.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: ap-south-1
          accessKeyIDSecretRef:
            name: aws-credentials-secret
            key: aws_access_key_id
          secretAccessKeySecretRef:
            name: aws-credentials-secret
            key: aws_secret_access_key
