apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: hello-kubernetes
  name: wildcard-certificate-prod
  namespace: cert-manager
spec:
  dnsNames:
  - "*.maifuj.com"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-cluster-issuer-llt
  secretName: wildcard-certificate-secret-prod
  usages:
  - digital signature
  - key encipherment
